yoshihiro-shu/tech-blog-backend

backend/cache/redis.go
backend/cache/redis_test.go
backend/go.mod
backend/go.sum

Add Redis Test

---

backend/auth/jwt.go
backend/auth/middleware.go
backend/controller/user.go
backend/handler/user.go
docker-compose-mac.yaml

AuthMiddlewareのリファクター
本当はテストもしたかった
将来的に、汎用性を高くするため
リファクター
* ユーザに影響すること
* メンバーに影響すること
* システムに影響すること
* 使い方
* 再現手順
* その他に伝えたいこと

Refactor user login function

---

.github/.workflows/build-test.yaml

* 変更の概要
Lintチェックを行うため、まず簡単にgithub workflowを利用し、ビルドチェックを行う。
* 変更をする理由
文法エラーなど単純なエラーを防ぐため。
将来的に本格的にgithub actionsを利用するために、テストを兼ねて
* ユーザに影響すること
* メンバーに影響すること
* システムに影響すること
* 使い方
* 再現手順
* 悩んでいること
* その他に伝えたいこと

ADD Build-Test CI

---

README.md
backend/request/json.go
backend/request/middleware.go

* 変更の概要
* 変更をする理由
* ユーザに影響すること
* メンバーに影響すること
* システムに影響すること
* 使い方
* 再現手順
* 悩んでいること
* その他に伝えたいこと

FIX CorsHeader

---

backend/domain/model/article.go
backend/interfaces/api/server/handler/top_page.go
backend/interfaces/api/server/request/json.go
backend/internal/model/article/table/type.go
migrations/20220901232246_create_article_table.sql
migrations/20220901234508_add_test_article.sql

* 変更の概要
* 変更をする理由
* ユーザに影響すること
* メンバーに影響すること
* システムに影響すること
* 使い方
* 再現手順
* 悩んでいること
* その他に伝えたいこと

add thumbnail in article table

---

backend/application/usecase/twitter.go
backend/configs.yaml
backend/domain/model/twitter.go
backend/domain/repository/twitter.go
backend/infrastructure/persistence/twitter.go
backend/interfaces/api/server/handler/top_page.go
backend/interfaces/api/server/handler/twitter.go
backend/interfaces/api/server/router/setRouters.go
backend/internal/config/new.go
backend/internal/twitter_api/client.go
backend/internal/twitter_api/tweet/timeline/user_timeline.go
backend/internal/twitter_api/utils/api.go
backend/internal/twitter_api/utils/auth.go
backend/internal/twitter_api/utils/url.go
backend/registory/twitter_registory.go

* 変更の概要
* 変更をする理由
* ユーザに影響すること
* メンバーに影響すること
* システムに影響すること
* 使い方
* 再現手順
* 悩んでいること
* その他に伝えたいこと

ADD Twitter API

---

docker-compose.yaml
migrations/.dockerignore
migrations/Dockerfile

* 変更の概要
* 変更をする理由
* ユーザに影響すること
* メンバーに影響すること
* システムに影響すること
* 使い方
* 再現手順
* 悩んでいること
* その他に伝えたいこと

ADD draft-migration image

---

backend/interfaces/api/server/request/json.go
backend/internal/pkg/logger/config.go

* 変更の概要
* 変更をする理由
* ユーザに影響すること
* メンバーに影響すること
* システムに影響すること
* 使い方
* 再現手順
* 悩んでいること
* その他に伝えたいこと

[FIX] timezone

---

backend/configs.yaml

* 変更の概要
* 変更をする理由
* ユーザに影響すること
* メンバーに影響すること
* システムに影響すること
* 使い方
* 再現手順
* 悩んでいること
* その他に伝えたいこと

ADD redis expires into configs.yaml

---

backend/cmd/main.go
backend/internal/config/auth.go
backend/internal/config/error.go
backend/internal/config/new.go
backend/internal/config/rdb.go
backend/internal/config/redis.go
backend/internal/config/server.go
backend/internal/config/twitter.go
backend/internal/pkg/logger/new.go

* 変更の概要
* 変更をする理由
* ユーザに影響すること
* メンバーに影響すること
* システムに影響すること
* 使い方
* 再現手順
* 悩んでいること
* その他に伝えたいこと

REFACTOR config pkg

---

.github/workflows/docker-app-push.yaml
.github/workflows/docker-migration-push.yaml

* 変更の概要
* 変更をする理由
* ユーザに影響すること
* メンバーに影響すること
* システムに影響すること
* 使い方
* 再現手順
* 悩んでいること
* その他に伝えたいこと

FIX github-action

---

backend/interfaces/api/server/middlewares/csrf.go

* 変更の概要
* 変更をする理由
* ユーザに影響すること
* メンバーに影響すること
* システムに影響すること
* 使い方
* 再現手順
* 悩んでいること
* その他に伝えたいこと

CSRF TokenのPOSTメソッド以外の対応

---

.github/workflows/go-build.yaml

* 変更の概要
* 変更をする理由
* ユーザに影響すること
* メンバーに影響すること
* システムに影響すること
* 使い方
* 再現手順
* 悩んでいること
* その他に伝えたいこと

FIX go build test

---

.github/workflows/go-build.yaml

Reverts yoshihiro-shu/draft-backend#36

Revert "FIX go build test"

---

nginx/conf.d/nginx.conf

* 変更の概要
* 変更をする理由
* ユーザに影響すること
* メンバーに影響すること
* システムに影響すること
* 使い方
* 再現手順
* 悩んでいること
* その他に伝えたいこと

httpを一時的に許可

---

backend/go.mod
backend/go.sum
backend/interfaces/api/server/request/bind.go
backend/interfaces/api/server/request/bind_test.go
backend/internal/mock_test/mock_cache.go
backend/internal/mock_test/mock_context.go
backend/internal/mock_test/mock_db.go

* 変更の概要
* 変更をする理由
* ユーザに影響すること
* メンバーに影響すること
* システムに影響すること
* 使い方
* 再現手順
* 悩んでいること
* その他に伝えたいこと

[ADD]Test for MustBind

---

backend/interfaces/api/server/request/bind_test.go

* 変更の概要
* 変更をする理由
* ユーザに影響すること
* メンバーに影響すること
* システムに影響すること
* 使い方
* 再現手順
* 悩んでいること
* その他に伝えたいこと

[FIX]Test for MustBind

---

.github/workflows/go-testing.yaml
backend/go.mod
backend/go.sum
backend/interfaces/api/server/auth/utils_test.go
backend/interfaces/api/server/cache/redis_test.go

* 変更の概要
* 変更をする理由
* ユーザに影響すること
* メンバーに影響すること
* システムに影響すること
* 使い方
* 再現手順
* 悩んでいること
* その他に伝えたいこと

[ADD]Test for bcrypt

---

backend/interfaces/api/server/cache/redis_test.go
backend/internal/mock_test/mock_cache.go
backend/internal/mock_test/mock_context.go

* 変更の概要
* 変更をする理由
* ユーザに影響すること
* メンバーに影響すること
* システムに影響すること
* 使い方
* 再現手順
* 悩んでいること
* その他に伝えたいこと

ADD mock redis

---

README.md

* 変更の概要
* 変更をする理由
* ユーザに影響すること
* メンバーに影響すること
* システムに影響すること
* 使い方
* 再現手順
* 悩んでいること
* その他に伝えたいこと

ADD: System Archtecture in README

---

.github/workflows/docker-migration-push.yaml

* 変更の概要
* 変更をする理由
* ユーザに影響すること
* メンバーに影響すること
* システムに影響すること
* 使い方
* 再現手順
* 悩んでいること
* その他に伝えたいこと

fix: dockerfile path

---

.github/workflows/docker-batch-qiita.yaml
.github/workflows/reviewdog.yaml
batch/qiita/ .dockerignore
batch/qiita/Dockerfile
docker.md

* 変更の概要
* 変更をする理由
* ユーザに影響すること
* メンバーに影響すること
* システムに影響すること
* 使い方
* 再現手順
* 悩んでいること
* その他に伝えたいこと

add: rust docker image

---

backend/go.sum

* 変更の概要
* 変更をする理由
* ユーザに影響すること
* メンバーに影響すること
* システムに影響すること
* 使い方
* 再現手順
* 悩んでいること
* その他に伝えたいこと

update: go sum

---

Dockerfile

* 変更の概要
* 変更をする理由
* ユーザに影響すること
* メンバーに影響すること
* システムに影響すること
* 使い方
* 再現手順
* 悩んでいること
* その他に伝えたいこと

update: docker image

---

Dockerfile

* 変更の概要
* 変更をする理由
buildステージにてtimezoneのpackageがなかったため、追加
* ユーザに影響すること
* メンバーに影響すること
* システムに影響すること
* 使い方
* 再現手順
* 悩んでいること
* その他に伝えたいこと

add: tzdata in image

---

.github/workflows/go-build.yaml
.github/workflows/go-testing.yaml
.tool-versions
Dockerfile
src/Dockerfile

* 変更の概要
GOのバージョンアップ
* 変更をする理由
* ユーザに影響すること
* メンバーに影響すること
* システムに影響すること
* 使い方
* 再現手順
* 悩んでいること
* その他に伝えたいこと

update: golang v1.22rc1

---

deployment/helm/tech-blog-backend/templates/service-monitor.yaml

* 変更の概要
* 変更をする理由
* ユーザに影響すること
* メンバーに影響すること
* システムに影響すること
* 使い方
* 再現手順
* 悩んでいること
* その他に伝えたいこと

add: service-monitor yaml

---

.github/workflows/docker-elasticsearch-push.yaml
images/elasticsearch/Dockerfile

* 変更の概要
* 変更をする理由
* ユーザに影響すること
* メンバーに影響すること
* システムに影響すること
* 使い方
* 再現手順
* 悩んでいること
* その他に伝えたいこと

add: elasticsearch image

---

.github/workflows/go-testing.yaml
src/application/usecase/profile.go
src/configs.yaml
src/domain/repository/profile.go
src/infrastructure/persistence/cache/keys.go
src/infrastructure/persistence/cache/profile.go
src/interfaces/api/handler/profile.go
src/interfaces/api/router/main.router.go
src/interfaces/api/router/profile.router.go
src/internal/config/github.go
src/internal/config/new.go
src/internal/github_api/client.go
src/internal/github_api/client_test.go
src/registory/profile_registory.go

* 変更の概要
* 変更をする理由
* ユーザに影響すること
* メンバーに影響すること
* システムに影響すること
* 使い方
* 再現手順
* 悩んでいること
* その他に伝えたいこと

add: get contents from github repo

---

Dockerfile
src/Dockerfile

* 変更の概要
* 変更をする理由
* ユーザに影響すること
* メンバーに影響すること
* システムに影響すること
* 使い方
* 再現手順
* 悩んでいること
* その他に伝えたいこと

update: base docker image 

---

.github/workflows/docker-app-push.yaml
.github/workflows/docker-batch-qiita.yaml
.github/workflows/docker-migration-push.yaml

* 変更の概要
* 変更をする理由
* ユーザに影響すること
* メンバーに影響すること
* システムに影響すること
* 使い方
* 再現手順
* 悩んでいること
* その他に伝えたいこと

change: docker registry -> ghr

---

.gitignore
src/.air.toml
src/Dockerfile
src/cmd/main.go

* 変更の概要
* 変更をする理由
* ユーザに影響すること
* メンバーに影響すること
* システムに影響すること
* 使い方
* 再現手順
* 悩んでいること
* その他に伝えたいこと

add: golang air
